---
# - hosts: all
#   become: yes
#   - name: upgrade all packages
#     yum:
#       name: '*'
#       state: latest
#     become: true


- hosts: client
  become: yes
  tasks:
  - name: client | Install packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - nginx  

  - name: client | Accept port 80 tcp 
    iptables:
      chain: INPUT
      protocol: tcp
      source_port: 80
      match: conntrack
      ctstate: ESTABLISHED
      jump: ACCEPT      

  - name: client | Accept port 80 tcp 
    iptables:
      chain: OUTPUT
      protocol: tcp
      destination_port: 80
      match: conntrack
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT      

  - name: client | Copy file 
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: client | Start Nginx
    systemd:
      name: nginx
      state: started
      enabled: yes

- hosts: server-log
  become: yes
  tasks:
  - name: server-log | Accept port 514 tcp udp
    iptables:
      chain: INPUT
      protocol: "{{ item }}"
      destination_port: 514
      jump: ACCEPT
    loop:
      - tcp
      - udp  

  - name: server-log | Copy file 
    copy:
      src: rsyslog.conf
      dest: /etc/rsyslog.conf   

  - name: server-log | Start Nginx
    systemd:
      name: rsyslog
      state: restarted

